[mcp_servers.edit-figure]
command = "/usr/bin/python3"
args = [
  "-s",
  "/kaggle/working/Edit-Figure-MCP/edit_figure_mcp_server.py"
]
cwd = "/kaggle/working/Edit-Figure-MCP"
startup_timeout_sec = 60
tool_timeout_sec = 600

[mcp_servers.edit-figure.env]
ROBOFLOW_API_KEY = "vJfqq4sPfI9zN2gAcAOe"